### ISSUE TITLE
gpio error

### ISSUE THREAD

**Issue by mthd98** [vitiral/gpio#15]
IndentationError('expected an indented block', ('<stdin>', 2, 4, 'gpio.set(255,0)\n'))
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/nvidia/.local/lib/python3.5/site-packages/gpio.py", line 19, in except_hook
    pdb.post_mortem(tb)
  File "/usr/lib/python3.5/pdb.py", line 1590, in post_mortem
    raise ValueError("A valid traceback must be passed if no "
ValueError: A valid traceback must be passed if no exception is being handled

Original exception was:
  File "<stdin>", line 2
    gpio.set(255,0)
       ^
IndentationError: expected an indented block
 how to fix it

**Comment by vitiral** [comment]
It looks like you wrote invalid python to me
